name: Go
on: [push]
jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/setup-go@v1
      with:
        go-version: 1.13

    - uses: actions/checkout@v1
 
    - name: build
      run: |
        export PATH=$PATH:$(go env GOPATH)/bin
        curl -L https://git.io/fjaxx | repo=ysmood/kit bin=godev sh
        godev lint
        godev test
    - uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
